### ISSUE TITLE
Packagist issue

### ISSUE THREAD

**Issue by mat-hew1** [nelsonglory/ng_fastyoutube#3]
Hi Roderick,
your extension ist very nice and helpful, but can you please use the right naming conventions for composer & packagist, no underscore in name but hyphen.
Can you plese use tagged versions of your project too, to use composer versioning instead of dev-master?
Thank you very much.

**Comment by nelsonglory** [comment]
Thanks, I changed the naming in composer.json and added tagged versions in git according to your proposals.
